#!/usr/bin/env bash
# Define the file name
FILE="school"

#check if the file exists
if [ -e "$FILE" ]; then
echo "school file exist"
else
echo "school file does not exist"
fi

# Check if the file is empty
if [ ! -s "$FILE" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi

# Check if the file is a regular file
if [ -f "$FILE" ]; then
echo "school is a regular file"
fi
